stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags: 
     - vm1
  script:
    - docker run -d --name docker-nginx -p 9889:80 nginx
    - curl -I http://84.201.175.159:9889/ 2>/dev/null | head -n 1 | cut -d$' ' -f2
